export default {
  OCEAN: 'OCEAN',
  SEA: 'SEA',
  DRY_SAND: 'DRY_SAND',
  SAND: 'SAND',
  WET_SAND: 'WET_SAND',
  DRY_GRASS: 'DRY_GRASS',
  GRASS: 'GRASS',
  WET_GRASS: 'WET_GRASS',
  MOUNTAIN_SNOW: 'MOUNTAIN_SNOW',
  MOUNTAIN_ORE: 'MOUNTAIN_ORE',
  MOUNTAIN: 'MOUNTAIN'
}
